#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Please use two arguments: ./addUnitsManual <FLUID> <GROUP>"
	exit
fi

./enterUnits $1 $2

echo "Adding units to mongodb"
cat unitsToAdd.js | mongo > /dev/null